[package]
name = "rusty-containers"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
tokio = { version = "1", features = ["macros"] }
bollard = "0.11"
futures-util = "0.3"
anyhow = "1.0"
log = "0.4"
env_logger = "0.9"
